# use the official node.js image with alphine linux as the base image
FROM node:24-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci --only=production


COPY . .

# RUN npm run build

EXPOSE 3002

CMD [ "node", "src/server.js" ]
