# use the official node.js image with alphine linux as the base image
FROM node:24-alpine

WORKDIR /use/src/app

COPY package*.json ./

RUN npm ci --only=production


COPY . .

# RUN npm run build

EXPOSE 3000

CMD [ "node", "src/server.js" ]
